export type KnowledgeDomain = "copywriting" | "psychology" | "awareness" | "persuasion" | "framework" | "advertising" | "cro" | "ugc" | "pricing" | "offers" | "testing";

export interface KnowledgeModule {
  id: string;
  domain: KnowledgeDomain;
  title: string;
  purpose: string;
  principles: string[];
  decisionRules: string[];
  appliesTo: string[];
  sourcePolicy: "original_synthesis" | "licensed" | "public_guidance" | "user_provided";
}

export const CORE_KNOWLEDGE_MODULES: KnowledgeModule[] = [
  { id: "direct-response", domain: "copywriting", title: "Direct-response copywriting", purpose: "Optimize messaging for a measurable customer action.", principles: ["Lead with a specific customer outcome", "Match proof to the claim", "Reduce friction before adding persuasion"], decisionRules: ["Prefer evidence-backed claims", "Adapt message complexity to awareness and intent"], appliesTo: ["ads", "landing_pages", "scripts", "offers"], sourcePolicy: "original_synthesis" },
  { id: "consumer-psychology", domain: "psychology", title: "Consumer psychology", purpose: "Model motivations, friction, perceived value and decision context.", principles: ["Separate motivation from mechanism", "Identify anxieties and desired outcomes", "Avoid unsupported psychological claims"], decisionRules: ["Use observed customer evidence when available", "Treat inferred motivations as hypotheses"], appliesTo: ["research", "positioning", "copy", "cro"], sourcePolicy: "original_synthesis" },
  { id: "schwartz-awareness", domain: "awareness", title: "Awareness-level framework", purpose: "Match messaging to how much the audience already knows about the problem and solution.", principles: ["Unaware needs education", "Problem-aware needs problem-to-solution movement", "Product-aware needs differentiation and proof"], decisionRules: ["Select the message before writing the hook", "Do not assume awareness without evidence"], appliesTo: ["strategy", "hooks", "ads", "landing_pages"], sourcePolicy: "original_synthesis" },
  { id: "cialdini", domain: "persuasion", title: "Persuasion principles", purpose: "Use ethical persuasion mechanisms without manufacturing evidence.", principles: ["Use credible social proof", "Make authority verifiable", "Use scarcity only when genuine"], decisionRules: ["Never fabricate proof, urgency or authority", "Prefer transparent persuasion"], appliesTo: ["offers", "ads", "landing_pages"], sourcePolicy: "original_synthesis" },
  { id: "aida", domain: "framework", title: "AIDA", purpose: "Structure attention, interest, desire and action when the sequence fits the customer journey.", principles: ["Earn attention with relevance", "Build desire with benefits and proof", "Make the next action clear"], decisionRules: ["Skip stages when audience intent already makes them unnecessary"], appliesTo: ["ads", "scripts", "landing_pages"], sourcePolicy: "original_synthesis" },
  { id: "pas", domain: "framework", title: "PAS", purpose: "Frame a problem, intensify its consequence responsibly, then present a solution.", principles: ["Use a real customer problem", "Do not exaggerate harm", "Connect solution to the stated problem"], decisionRules: ["Require evidence for strong problem claims"], appliesTo: ["hooks", "ads", "scripts"], sourcePolicy: "original_synthesis" },
  { id: "storybrand", domain: "framework", title: "Story-based customer framing", purpose: "Keep the customer as the protagonist and the product as the guide/tool.", principles: ["Clarify the customer's desired outcome", "Show the guide's role", "Provide a clear plan and action"], decisionRules: ["Avoid making the brand the hero when customer agency matters"], appliesTo: ["landing_pages", "brand", "scripts"], sourcePolicy: "original_synthesis" },
  { id: "meta-ads", domain: "advertising", title: "Meta advertising principles", purpose: "Create platform-aware, policy-conscious acquisition strategies.", principles: ["Optimize for the selected business outcome", "Maintain message-to-landing-page consistency", "Test creative variables deliberately"], decisionRules: ["Separate platform constraints from strategic recommendations", "Never invent performance benchmarks"], appliesTo: ["campaigns", "creative", "analytics"], sourcePolicy: "public_guidance" },
  { id: "tiktok-creative", domain: "advertising", title: "Short-form creative principles", purpose: "Design native-feeling short-form concepts with rapid value communication.", principles: ["Front-load the premise", "Design for sound-off comprehension", "Use authentic demonstrations where appropriate"], decisionRules: ["Use current platform guidance through a research adapter rather than stale hard-coded claims"], appliesTo: ["video", "ugc", "hooks"], sourcePolicy: "public_guidance" },
  { id: "landing-cro", domain: "cro", title: "Landing-page CRO", purpose: "Reduce friction and improve message continuity and clarity.", principles: ["Match headline to acquisition promise", "Make proof easy to find", "Reduce unnecessary decision friction"], decisionRules: ["Prioritize high-impact hypotheses", "Do not claim uplift without experiment data"], appliesTo: ["landing_pages", "funnels", "experiments"], sourcePolicy: "original_synthesis" },
  { id: "ugc", domain: "ugc", title: "UGC creative frameworks", purpose: "Structure creator-style concepts around authentic experience and product demonstration.", principles: ["Lead with a believable customer moment", "Show rather than merely claim", "Keep creator voice natural"], decisionRules: ["Do not fabricate testimonials or personal experience", "Clearly distinguish generated concepts from real customer testimony"], appliesTo: ["ugc", "video", "ads"], sourcePolicy: "original_synthesis" },
  { id: "pricing-psychology", domain: "pricing", title: "Pricing psychology", purpose: "Evaluate perceived value, price framing and friction ethically.", principles: ["Anchor against relevant value", "Make price structure transparent", "Use risk reversal only when real"], decisionRules: ["Never manufacture discounts or false reference prices"], appliesTo: ["offers", "landing_pages", "ads"], sourcePolicy: "original_synthesis" },
  { id: "offer-creation", domain: "offers", title: "Offer creation", purpose: "Build a compelling offer from real product value, proof and risk reduction.", principles: ["Increase relevant value before adding complexity", "Bundle only useful components", "Make constraints explicit"], decisionRules: ["Every bonus/guarantee/urgency element must be factually available"], appliesTo: ["offers", "strategy", "landing_pages"], sourcePolicy: "original_synthesis" },
  { id: "creative-testing", domain: "testing", title: "Creative testing frameworks", purpose: "Design experiments that isolate meaningful creative variables and generate reusable learning.", principles: ["Define the hypothesis before launch", "Change one primary variable where practical", "Record audience, spend and context"], decisionRules: ["Do not over-interpret small samples", "Promote learnings to memory only with confidence metadata"], appliesTo: ["experiments", "analytics", "learning"], sourcePolicy: "original_synthesis" },
];
